name: Check Markdown Links

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lychee:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: 🔗 Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: >-
            --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
            --exclude "https?://(www\.)?(twitter\.com|x\.com|instagram\.com|linkedin\.com)"
            --threads 2
            --max-redirects 10
            --max-retries 2
            --max-concurrency 14
            --timeout 20
            --retry-wait-time 2
            --accept 200,429
            --method get
            "./docs/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
